ALTER TABLE public.members
    ADD COLUMN pid VARCHAR(32) NOT NULL DEFAULT '',
    ADD COLUMN email VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN phone_number VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN address VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN zip_code VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN city VARCHAR(255) NOT NULL DEFAULT '';
